# Generated by Django 4.0.5 on 2022-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата написании книги'),
        ),
    ]
