# Generated by Django 4.0.5 on 2022-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, height_field=350, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Ссылка на изображение', width_field=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books.author'),
        ),
    ]
