# Generated by Django 4.0.5 on 2022-06-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_img_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_img',
        ),
    ]
